Direct socket-based communication
AG-Schumann/Doberman pull request #142
Opened 2022-01-17 10:50 UTC by darrylmasson

Rather than having everything poke the database once per second to see if there are new commands, it is much faster to have things communicate directly. This PR rewrites the command subsystem to enable this. All Monitors now have a Listener, which picks an open port and listens for incoming commands. The hypervisor has a Dispatcher, which acts as an intermediary between things to facilitate delayed commands. All commands are routed via the dispatcher, which maintains an internal queue. Assuming the rate of internal message-passing doesn't exceed 10s of messages per second, no bottlenecking is expected.

2022-01-17 14:26 UTC, jarongrigat requested changes

2022-01-17 14:26 UTC, jarongrigat commented on Doberman/utils.py
> +            for i in itertools.count(2):
`import itertools`

2022-01-17 14:26 UTC, jarongrigat commented on Doberman/hypervisor.py
> +                    with socket.create_connection((hn, p), timeout=0.1) as sock:
`import socket`

2022-01-17 14:26 UTC, jarongrigat commented on Doberman/hypervisor.py
> +                self.dispatch_queue.add(json.loads(command))
`import json`

2022-01-18 10:58 UTC, jarongrigat approved these changes

2022-02-02 09:46 UTC, darrylmasson commented
Ok, I think we're ready to merge

2022-02-02 09:46 UTC, merged